version: "3"
services:
  nginx:
    image: nginx:latest
    # Uses local nginx.conf
    networks:
      - network.local
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf    
    ports:
      - 80:80
      - 443:443
networks:
  network.local:
